version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flight-search-service:
    build: ./flight-search-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/flight-search
    depends_on:
      - mongodb

volumes:
  mongo_data: