version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flight-search-service:
    build: ./flight-search-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/flight-search
    depends_on:
      - mongodb

  booking-service:
    build: ./booking-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/booking-service
      - REDIS_URI=redis://redis:6379
      - FLIGHT_SERVICE_URL=http://flight-search-service:3001
    depends_on:
      - mongodb
      - redis
      - flight-search-service

volumes:
  mongo_data:
  redis_data: